name: file-sharing
services:
  app:
    image: "ghcr.io/rpungello/file-sharing:${IMAGE_TAG:-latest}"
    env_file: stack.env
    ports:
      - '${WEB_PORT:-80}:8000'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/up"]
